### PR TITLE
Error: PublishError.InsufficientPeers

### PR DESCRIPTION
**Pull request by koh-osug**
Prevent Error: PublishError.InsufficientPeers when starting alone

### CODE REVIEW

**Comment by haydenyoung** [comment]
Closing as no correspondence on requested changes. Please feel free to re-open if you would still like to make the requested updates and submit an updated PR.

**Comment by koh-osug** [comment]
I have seen no comment or changes here. What are the requested updates?

**Comment by haydenyoung** [comment]
> I have seen no comment or changes here. What are the requested updates?

Please see https://github.com/orbitdb/orbitdb/pull/1149/files/5f13b5f2fc501172a5edebae77ff49145cb4bc2c

**Comment by koh-osug** [comment]
> > I have seen no comment or changes here. What are the requested updates?
> 
> Please see https://github.com/orbitdb/orbitdb/pull/1149/files/5f13b5f2fc501172a5edebae77ff49145cb4bc2c

Have you finished your review? I cannot see any review items.

**Review by haydenyoung — CHANGES_REQUESTED** [review]

**Comment by haydenyoung** [comment]
@koh-osug can you see the change request above?

**Comment by koh-osug** [comment]
> @koh-osug can you see the change request above?

Yes, it works now.

**Comment by koh-osug** [comment]
Updated

**Comment by haydenyoung** [comment]
@koh-osug 

Not seeing any tab formatting changes. Currently seeing:

```
const Libp2pOptions = {
        services: {
          pubsub: gossipsub({
            // neccessary to run a single peer
            allowPublishToZeroPeers: true
          }),
          identify: identify()
        }
    }
```
Should be something like:
```
const Libp2pOptions = {
  services: {
    pubsub: gossipsub({
      // neccessary to run a single peer
      allowPublishToZeroPeers: true
    }),
    identify: identify()
  }
}
```
(2 space tab).

**Comment by koh-osug** [comment]
Ok, another try. I thought more spaces are needed.

**Comment by haydenyoung** [comment]
Looks great. Thanks.

**Pull request merged**
